### ISSUE TITLE
Question about including libopenmpt_py in a project / license

### ISSUE THREAD

**Issue by knochenhans** [shroom00/libopenmpt_py#1]
Hi, I’m currently working on a Python MOD player (https://github.com/knochenhans/modarchive-random-player) that uses libopenmpt and libuade as backends. I’d love to include libopenmpt_py directly, if possible, as it’s not available via pip. For now, users would have to manually download libopenmpt_py and add it via command line argument to my player which feels awkward. Would you mind if I include your code in my repository and mention it in my readme?

I’m not seeing any licensing information for your project, so I thought I’d better ask :)

**Comment by shroom00** [comment]
Feel free to use it, as long as you provide credit that's fine! I'll add a license later and get to work sorting pip stuff out in the meantime. Thanks for asking :)
